default: styles/application.scss
contrast: styles/contrast.scss
MstdnArea: styles/kemo.scss
MstdnArea2: styles/kemo2.scss
MstdnBlue: styles/mstdn.scss
mastodon-light: styles/mastodon-light.scss
C0ffee: styles/coffee.scss
