name: Build container image
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "*"
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: maa123
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/maa123/mastodon
          flavor: |
            latest=auto
          tags: |
            type=edge,branch=master
            type=semver,pattern={{ raw }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=ghcr.io/maa123/mastodon:latest
          cache-to: type=inline
